index:
    path: /
    controller: App\Controller\HomeController::home

Login_page:
  path: /crud/product
  controller: App\Controller\CrudProductController::index

Home_page:
  path: /login
  controller: App\Controller\SecurityController::login

Register_page:
  path: /register
  controller: App\Controller\ResistrationController::register